import 'package:flutter/material.dart';
import 'strings.dart';

enum Mechanic {
  pattern,
  farm,
  rhythm,
  market,
  bamboo,
  puzzle,
  who,
  where,
  there,
  timeline,
  detective,
  quiz,
  tune,
  thenNow,
  proverb,
  chain,
  match,
  search,
  sound,
  recall,
  number,
  shape,
}

class Game {
  final String id, en, as, bn, domain;
  final Mechanic mechanic;
  final IconData icon;
  final int category;
  const Game(
    this.id,
    this.en,
    this.as,
    this.bn,
    this.domain,
    this.mechanic,
    this.icon,
    this.category,
  );
  String title(Words w) => w.text(en, as, bn);
  bool get family => category == 1;
}

const catalog = [
  Game(
    'jigsaw',
    'Piece by piece',
    'ছবি সজাওক',
    'ছবি সাজান',
    'spatial',
    Mechanic.puzzle,
    Icons.extension_outlined,
    0,
  ),
  Game(
    'weaving',
    'Weaving pattern',
    'বয়নৰ আৰ্হি',
    'বুননের নকশা',
    'attention',
    Mechanic.pattern,
    Icons.grid_view_rounded,
    0,
  ),
  Game(
    'farm',
    'Farm to kitchen',
    'পথাৰৰ পৰা পাকঘৰলৈ',
    'মাঠ থেকে রান্নাঘর',
    'sequencing',
    Mechanic.farm,
    Icons.grass_rounded,
    0,
  ),
  Game(
    'rhythm',
    'Rhythm repeat',
    'তাল মিলাওক',
    'তাল মেলান',
    'memory',
    Mechanic.rhythm,
    Icons.music_note_rounded,
    0,
  ),
  Game(
    'market',
    'Market day',
    'বজাৰৰ দিন',
    'বাজারের দিন',
    'calculation',
    Mechanic.market,
    Icons.shopping_basket_outlined,
    0,
  ),
  Game(
    'bamboo',
    'Bamboo builder',
    'বাঁহৰ খেল',
    'বাঁশের খেলা',
    'spatial',
    Mechanic.bamboo,
    Icons.architecture_rounded,
    0,
  ),
  Game(
    'who',
    'Who is this?',
    'এওঁ কোন?',
    'ইনি কে?',
    'memory',
    Mechanic.who,
    Icons.person_outline_rounded,
    1,
  ),
  Game(
    'where',
    'Where were we?',
    'আমি ক’ত আছিলোঁ?',
    'আমরা কোথায় ছিলাম?',
    'memory',
    Mechanic.where,
    Icons.place_outlined,
    1,
  ),
  Game(
    'there',
    'Who was there?',
    'তাত কোন আছিল?',
    'সেখানে কে ছিল?',
    'memory',
    Mechanic.there,
    Icons.people_outline_rounded,
    1,
  ),
  Game(
    'timeline',
    'Family timeline',
    'পৰিয়ালৰ সময়ৰেখা',
    'পরিবারের সময়রেখা',
    'sequencing',
    Mechanic.timeline,
    Icons.timeline_rounded,
    1,
  ),
  Game(
    'detective',
    'Photo detective',
    'ফটোৰ ৰহস্য',
    'ছবির রহস্য',
    'memory',
    Mechanic.detective,
    Icons.search_rounded,
    1,
  ),
  Game(
    'quiz',
    'Family quiz',
    'পৰিয়ালৰ প্ৰশ্ন',
    'পরিবারের প্রশ্ন',
    'memory',
    Mechanic.quiz,
    Icons.forum_outlined,
    1,
  ),
  Game(
    'tune',
    'Name that tune',
    'সুৰটো চিনি পাওক',
    'সুরটি চিনুন',
    'memory',
    Mechanic.tune,
    Icons.piano_outlined,
    2,
  ),
  Game(
    'then',
    'Then and now',
    'তেতিয়া আৰু এতিয়া',
    'তখন ও এখন',
    'attention',
    Mechanic.thenNow,
    Icons.compare_outlined,
    2,
  ),
  Game(
    'proverb',
    'Complete the proverb',
    'ফকৰা সম্পূৰ্ণ কৰক',
    'প্রবাদ সম্পূর্ণ করুন',
    'language',
    Mechanic.proverb,
    Icons.chat_bubble_outline_rounded,
    2,
  ),
  Game(
    'traditional',
    'Traditional pattern',
    'পৰম্পৰাগত আৰ্হি',
    'ঐতিহ্যবাহী নকশা',
    'attention',
    Mechanic.pattern,
    Icons.texture_rounded,
    2,
  ),
  Game(
    'chain',
    'Memory chain',
    'স্মৃতিৰ শিকলি',
    'স্মৃতির শিকল',
    'memory',
    Mechanic.chain,
    Icons.link_rounded,
    2,
  ),
  Game(
    'match',
    'Quick match',
    'ছবি মিলাওক',
    'ছবি মেলান',
    'attention',
    Mechanic.match,
    Icons.filter_none_rounded,
    3,
  ),
  Game(
    'search',
    'Find it',
    'বিচাৰি উলিয়াওক',
    'খুঁজে দেখুন',
    'attention',
    Mechanic.search,
    Icons.manage_search_rounded,
    3,
  ),
  Game(
    'sound',
    'Sound match',
    'শব্দ মিলাওক',
    'শব্দ মেলান',
    'attention',
    Mechanic.sound,
    Icons.hearing_rounded,
    3,
  ),
  Game(
    'recall',
    'Remember the pictures',
    'ছবিবোৰ মনত ৰাখক',
    'ছবিগুলি মনে রাখুন',
    'memory',
    Mechanic.recall,
    Icons.psychology_outlined,
    3,
  ),
  Game(
    'number',
    'Number tap',
    'সংখ্যা চুই যাওক',
    'সংখ্যা ছুঁয়ে যান',
    'sequencing',
    Mechanic.number,
    Icons.pin_outlined,
    3,
  ),
  Game(
    'shape',
    'Colour and shape',
    'ৰং আৰু আকৃতি',
    'রং ও আকার',
    'attention',
    Mechanic.shape,
    Icons.category_outlined,
    3,
  ),
  Game(
    'speed',
    'Gentle jigsaw',
    'লাহে লাহে ছবি সজাওক',
    'ধীরে ছবি সাজান',
    'spatial',
    Mechanic.puzzle,
    Icons.widgets_outlined,
    3,
  ),
];
